services:
  database:
    image: mysql:lts-oraclelinux9
    container_name: mysql_container
    restart: always
    ports:
      - 3307:3306
#    volumes:
#      - /mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sustentify_db

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    depends_on:
      - database

volumes:
  dbbase: