services:
  web: 
    build: 
      context: ../../web
      dockerfile: Dockerfile
    container_name: sustentify-web
    ports:
      - 80:80
    # networks:
    #   - assistant-network
    #   - server-network

# networks:
#   assistant-network:
#     external: true
#   server-network:
#     external: true