services:
  database:
    image: mysql:lts-oraclelinux9
    container_name: mysqldb
    ports:
      - 3307:3306
#    volumes:
#      - /mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - server_net

  redis:
    image: redis:latest
    container_name: redisdb
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    networks:
      - server_net

  server:
    build:
      context: ../../services/server
      dockerfile: Dockerfile
    container_name: sustentify-server
    ports:
      - 8080:8080
    environment:
      - PORT=${SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - API_CORS_ORIGIN=${API_CORS_ORIGIN}
      - WEB_DOMAIN=${WEB_DOMAIN}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      # DEFAULT DOCKER
      # - MAIL_TEMPLATES_PATH=/usr/src/server/templates/mail-templates/
      - MAIL_TEMPLATES_PATH=${MAIL_TEMPLATES_PATH}
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - server_net
      - shared_net
      - observability_net
  
networks:
  server_net:
    driver: bridge
  observability_net:
    external: true
  shared_net:
    external: true