services:
  web: 
    build: 
      context: ../../services/web
      dockerfile: Dockerfile
      args:
        - NG_SUS_API_BASE_URL=${NG_SUS_API_BASE_URL}
        - NG_SUS_ASSISTANT_BASE_URL=${NG_SUS_ASSISTANT_BASE_URL}
        - NG_SUS_APP_VERSION=${NG_SUS_APP_VERSION}
        - NG_SUS_MAKE_REQUEST=${NG_SUS_MAKE_REQUEST}
    # image: guiferreiraa/sustentify-web:latest
    container_name: sustentify-web
    ports:
      - '80:80'
    networks:
      - shared_net

networks:
  shared_net:
    external: true