services:
  database:
    image: mysql:lts-oraclelinux9
    container_name: mysql_container
    restart: always
    ports:
      - 3307:3306
    #    volumes:
    #      - /mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sustentify_db
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    depends_on:
      - database

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=yourpassword
    restart: always