name: Deploy Server to Docker Hub

on: 
  push: 
    paths: 
      - 'server/**'
      - 'docker-compose.yaml'
    branches:
      - master
    tags:
      - 'v*'

jobs: 
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

  deploy-docker-hub:
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    needs: build-application
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4 

      - name: Login Docker Hub
        run: |
          echo ${{ env.DOCKER_HUB_PASSWORD }} | docker login -u ${{ env.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Extract Tag
        id: extract_tag
        run: |
          # Habilitar o modo de falha para qualquer erro
          set -e
          # Remover refs/heads/ para branch ou refs/tags/ para tags
          TAG=$(echo ${GITHUB_REF} | sed 's/refs\/\(heads\|tags\)\///')
          # Verificar se a tag contém / ou : e substituí-los por -
          TAG=${TAG//\//-}
          TAG=${TAG//:/-}
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
            docker build -t ${{ env.DOCKER_HUB_USERNAME }}/sustentify-server:${{ env.TAG }} ./server

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/sustentify-server:${{ env.TAG }}

      - name: Logout Docker Hub
        run: |
          docker logout