name: Deploy Assistant to Docker Hub

on: 
  push: 
    paths: 
      - 'chat/**'
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: docker-hub-assistant
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./chat

  deploy-docker-hub-latest:
    environment: docker-hub-assistant
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_PROJECT_NAME: ${{ secrets.DOCKER_HUB_PROJECT_NAME }}
    needs: build-main
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4 

      - name: Login Docker Hub
        run: |
          echo ${{ env.DOCKER_HUB_PASSWORD }} | docker login -u ${{ env.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_PROJECT_NAME }}:latest ./chat

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_PROJECT_NAME }}:latest

      - name: Logout Docker Hub
        run: |
          docker logout

  build-release-tag:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: docker-hub-assistant
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./chat

  deploy-docker-hub-with-tag:
    environment: docker-hub-assistant
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_PROJECT_NAME: ${{ secrets.DOCKER_HUB_PROJECT_NAME }}
    needs: build-release-tag
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4 

      - name: Login Docker Hub
        run: |
          echo ${{ env.DOCKER_HUB_PASSWORD }} | docker login -u ${{ env.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Extract Tag
        id: tag
        uses: aaronbarnaby/get-tag@v1.2.0
        with:
          without_prefix_v: true # Remove prefix `v` from tag
        
      - name: Set Git Tag Name
        run: echo "GIT_TAG_NAME=${{ steps.tag.outputs.tag }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_PROJECT_NAME }}:latest \
            -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_PROJECT_NAME }}:$GIT_TAG_NAME \
            ./chat

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_PROJECT_NAME }}:latest

          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_PROJECT_NAME }}:$GIT_TAG_NAME

      - name: Logout Docker Hub
        run: |
          docker logout