name: Deploy Server to Docker Hub

on: 
  push: 
    paths: 
      - 'server/**'
      - 'infra/docker-compose.yaml'
    branches:
      - main
    tags:
      - 'v*'
jobs: 
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4    
       
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
        
  deploy-docker-hub:
    environment: docker-hub-server
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_PROJECT_NAME: ${{ secrets.DOCKER_HUB_PROJECT_NAME }}
    needs: build-application
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4 

      - name: Login Docker Hub
        run: |
          echo ${{ env.DOCKER_HUB_PASSWORD }} | docker login -u ${{ env.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Extract Tag
        id: tag
        uses: aaronbarnaby/get-tag@v1.2.0
        with:
          without_prefix_v: true # Remove prefix `v` from tag
        
      - name: Set Git Tag Name
        run: echo "GIT_TAG_NAME=${{ steps.tag.outputs.tag }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_PROJECT_NAME }}:latest \
          -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_PROJECT_NAME }}:$GIT_TAG_NAME ./server

      - name: Push Docker image to Docker Hub
        run: |

          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_PROJECT_NAME }}:latest

          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_PROJECT_NAME }}:$GIT_TAG_NAME

      - name: Logout Docker Hub
        run: |
          docker logout